spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:dev
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
app:
  rest:
    youtube:
      secret-api: AIzaSyAC4SCNAUphENAyZZllQaSp1V6tJ54V2A4
      channel: UCA2tFk2NdzOzKpSJdf24cAg
      request-url: https://youtube.googleapis.com/youtube/v3/